name: ▷ Project Details and Reference
description: Create a project details reference issue. This issue persists for the life of a project and includes important project info, links and other resources.
title: '▷ PROJECT DETAILS AND REFERENCE'
labels: ['info']
body:
  - type: markdown
    attributes:
      value: "Please provide as much information as is available."
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the full name of the project
      placeholder: e.g., ACME Corp Website
    validations:
      required: true
  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: "Describe the project in as much detail as required to have an understanding of main goals for both client and Edgeworks Creative."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Project Deadlines & Billing"
  - type: input
    id: project_deadline
    attributes:
      label: Project Deadline
      description: Enter the project due date
      placeholder: July 01, 2024
  - type: input
    id: project_harvest
    attributes:
      label: Harvest Project Code
      description: Enter the Harvest Porject info
  - type: markdown
    attributes:
      value: "## Developer Info and Resources"
  - type: input
    id: project_xd
    attributes:
      label: XD Design Document Link
      description: Enter the XD Design Document Link
  - type: input
    id: project_sheet
    attributes:
      label: Client Project Sheet
      description: URL to the client project sheet (if any)
  - type: input
    id: project_staged
    attributes:
      label: Stage Development Server URL
      description: URL to the live Dev Server
  - type: input
    id: project_live_url
    attributes:
      label: Live Website URL
      description: The live website URL