name: ▷ PROJECT DETAILS AND REFERENCE
description: Create a project details reference with project description and links to important resources.
title: '▷ PROJECT DETAILS AND REFERENCE'
labels: ['info']
body:
  - type: markdown
    attributes:
      value: "Please provide as much information as is available."
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the full name of the project
      placeholder: e.g., ACME Corp Website
    validations:
      required: true
  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: "Describe the project in as much detail as required to have an understanding of main goals for both client and Edgeworks Creative."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Project Deadlines & Billing
        Project Deadline:

        Harvest Project / Task:
        ## DEVELOPER INFO & RESOURCES

        XD Design Document Link: [ insert link here ]

        Client-Facing Project Sheet: [ insert link here ]

        Staged Development Server URL: [ none yet ]

        Live Website URL: